name: Run API and UI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      json-server:
        image: clue/json-server
        ports:
          - 3001:80
        options: --name Mock-API

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Install json-server
        run: npm install -g json-server

      - name: Start mock API server
        run: |
          json-server --watch Mock-API/db.json --port 3000 &
          sleep 5

      - name: Run tests
        run: |
          pytest Api-Tests/ -v
